export const LCWTM =
[ { url: 'https://www.podbean.com/ew/dir-mvwfy-6461849',
    text: 'S6E8: How to Market Yourself Online as a Niche Freelancer with Kyle Prinsloo',
    Broadcast_date: '2019-06-04' },
  { url: 'https://www.podbean.com/ew/dir-g3jak-63bbfb2',
    text: 'S6E7: How to Combine Your Passions to Create Your Own Career in Tech with Masha Zvereva',
    Broadcast_date: '2019-05-28' },
  { url: 'https://www.podbean.com/ew/dir-3us5b-62e5657',
    text: 'S6E6: Digital Literacy and the History of the Internet with Chris Castiglione',
    Broadcast_date: '2019-05-21' },
  { url: 'https://www.podbean.com/ew/dir-kb36r-624dcd7',
    text: 'S6E5: How One Airport Security Officer Became an IT Solutions Specialist with Samit Saini',
    Broadcast_date: '2019-05-14' },
  { url: 'https://www.podbean.com/ew/dir-mcfxb-61a301d',
    text: 'S6E4: Web Development, JavaScript and Building an Online Presence with Wes Bos',
    Broadcast_date: '2019-05-07' },
  { url: 'https://www.podbean.com/ew/dir-drrn2-6146753',
    text: 'Tech Toolbox 2019: The Fastest Way to Become a Developer (Even as a Beginner) with Imtiaz Ahmad',
    Broadcast_date: '2019-05-03' },
  { url: 'https://www.podbean.com/ew/dir-v6hnf-612e89d',
    text: 'Tech Toolbox 2019: Learning to Code How Online Education Has Evolved with Mark Lassoff',
    Broadcast_date: '2019-05-02' },
  { url: 'https://www.podbean.com/ew/dir-u3fyk-61166c9',
    text: 'Tech Toolbox 2019: Jumpstart Your Freelance Developer Career with Hahna Kane Latonick',
    Broadcast_date: '2019-05-01' },
  { url: 'https://www.podbean.com/ew/dir-y67nz-60fac6e',
    text: 'Tech Toolbox 2019: How to Learn Development Fundamentals with Michael Hartl',
    Broadcast_date: '2019-04-30' },
  { url: 'https://www.podbean.com/ew/dir-8j45g-60dcc73',
    text: 'Tech Toolbox 2019: How to Find Your Tech Career Fit with Jeremy Schifeling',
    Broadcast_date: '2019-04-29' } ]

